kind: pipeline
name: default

steps:
  - name: submodules
    image: docker:git
    commands:
      - apk add --update openssl 
      - mkdir ~/.ssh
      - chmod 700 ~/.ssh
      - ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
      - eval `ssh-agent -s`
      - openssl aes-256-cbc -md sha256 -d -in "$(pwd)/ci/.ssh/id_rsa.enc" -pass "pass:$DECRYPT_KEY" | ssh-add -
      - git submodule update --init --recursive --remote
    environment:
      DECRYPT_KEY:
        from_secret: "DECRYPT_KEY"
  - name: build
    image: node:latest
    commands:
      - npm ci
      - bash ./ci/gh-pages.sh
    environment:
      DECRYPT_KEY:
        from_secret: "DECRYPT_KEY"
      COMMIT_AUTHOR_EMAIL: "sh@signalwerk.ch"
      DEPLOY_DIR: "dist"
    when:
      branch:
        - master
